---
sudo: required
dist: bionic

language: go

env:
  - GO111MODULE=on

addons:
  apt:
    packages:
      - docker.io

script:
  - go version
  - go mod edit --replace github.com/gophercloud/gophercloud=github.com/mcsps/gophercloud@91a789f0d1566e938d4ec343bb4ffe0fcf597b47
  - make image-controller-manager
