---
dist: bionic

language: go

env: GO111MODULE=on GOFLAGS='-mod vendor'

go:
  - 1.14

install:
  - apt update && apt install -y docker.io

script:
  - go version
  - go mod edit --replace github.com/gophercloud/gophercloud=github.com/mcsps/gophercloud@91a789f0d1566e938d4ec343bb4ffe0fcf597b47
  - mkdir -p /go/src/k8s.io
  - cp -r /builds/mcsps/cloud-provider-openstack /go/src/k8s.io/cloud-provider-openstack
  - cd /go/src/k8s.io/cloud-provider-openstack
